// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gaia/doom/v1/doom.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Button is a bit index into the button mask carried by MsgInput. The mask is
// edge-triggered: the engine sees a key press when a bit goes 0 -> 1 and a key
// release when it goes 1 -> 0, so holding fire means setting BUTTON_FIRE in
// every tic's mask.
type Button int32

const (
	BUTTON_FORWARD      Button = 0
	BUTTON_BACKWARD     Button = 1
	BUTTON_TURN_LEFT    Button = 2
	BUTTON_TURN_RIGHT   Button = 3
	BUTTON_STRAFE_LEFT  Button = 4
	BUTTON_STRAFE_RIGHT Button = 5
	BUTTON_FIRE         Button = 6
	BUTTON_USE          Button = 7
	BUTTON_RUN          Button = 8
	BUTTON_STRAFE       Button = 9
	BUTTON_ESCAPE       Button = 10
	BUTTON_ENTER        Button = 11
	BUTTON_MAP          Button = 12
	BUTTON_YES          Button = 13
	BUTTON_NO           Button = 14
	BUTTON_WEAPON_1     Button = 15
	BUTTON_WEAPON_2     Button = 16
	BUTTON_WEAPON_3     Button = 17
	BUTTON_WEAPON_4     Button = 18
	BUTTON_WEAPON_5     Button = 19
	BUTTON_WEAPON_6     Button = 20
	BUTTON_WEAPON_7     Button = 21
)

var Button_name = map[int32]string{
	0:  "BUTTON_FORWARD",
	1:  "BUTTON_BACKWARD",
	2:  "BUTTON_TURN_LEFT",
	3:  "BUTTON_TURN_RIGHT",
	4:  "BUTTON_STRAFE_LEFT",
	5:  "BUTTON_STRAFE_RIGHT",
	6:  "BUTTON_FIRE",
	7:  "BUTTON_USE",
	8:  "BUTTON_RUN",
	9:  "BUTTON_STRAFE",
	10: "BUTTON_ESCAPE",
	11: "BUTTON_ENTER",
	12: "BUTTON_MAP",
	13: "BUTTON_YES",
	14: "BUTTON_NO",
	15: "BUTTON_WEAPON_1",
	16: "BUTTON_WEAPON_2",
	17: "BUTTON_WEAPON_3",
	18: "BUTTON_WEAPON_4",
	19: "BUTTON_WEAPON_5",
	20: "BUTTON_WEAPON_6",
	21: "BUTTON_WEAPON_7",
}

var Button_value = map[string]int32{
	"BUTTON_FORWARD":      0,
	"BUTTON_BACKWARD":     1,
	"BUTTON_TURN_LEFT":    2,
	"BUTTON_TURN_RIGHT":   3,
	"BUTTON_STRAFE_LEFT":  4,
	"BUTTON_STRAFE_RIGHT": 5,
	"BUTTON_FIRE":         6,
	"BUTTON_USE":          7,
	"BUTTON_RUN":          8,
	"BUTTON_STRAFE":       9,
	"BUTTON_ESCAPE":       10,
	"BUTTON_ENTER":        11,
	"BUTTON_MAP":          12,
	"BUTTON_YES":          13,
	"BUTTON_NO":           14,
	"BUTTON_WEAPON_1":     15,
	"BUTTON_WEAPON_2":     16,
	"BUTTON_WEAPON_3":     17,
	"BUTTON_WEAPON_4":     18,
	"BUTTON_WEAPON_5":     19,
	"BUTTON_WEAPON_6":     20,
	"BUTTON_WEAPON_7":     21,
}

func (x Button) String() string {
	return proto.EnumName(Button_name, int32(x))
}

func (Button) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d53e7c725f3a5c97, []int{0}
}

// Params configures the game the chain is running.
type Params struct {
	// sha256 of the IWAD the node must load, hex encoded. Every node has to feed
	// the engine the same WAD or the sim diverges, so the hash is consensus data
	// even though the file itself is not.
	WadHash string `protobuf:"bytes,1,opt,name=wad_hash,json=wadHash,proto3" json:"wad_hash,omitempty"`
	// How many game tics to advance per block. DOOM's native rate is 35 tics/s,
	// so 1 tic per block wants ~28ms blocks. Bump this if the chain runs slower.
	TicsPerBlock uint32 `protobuf:"varint,2,opt,name=tics_per_block,json=ticsPerBlock,proto3" json:"tics_per_block,omitempty"`
	// How many past tics of input to keep, 0 for all of them. Keeping all of
	// them is what lets a restarted node rebuild the game by replaying from tic
	// 0; prune and you trade that away for disk.
	InputHistory uint64 `protobuf:"varint,3,opt,name=input_history,json=inputHistory,proto3" json:"input_history,omitempty"`
	// Address allowed to send MsgInput. Empty means anybody can play.
	Controller string `protobuf:"bytes,4,opt,name=controller,proto3" json:"controller,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_d53e7c725f3a5c97, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetWadHash() string {
	if m != nil {
		return m.WadHash
	}
	return ""
}

func (m *Params) GetTicsPerBlock() uint32 {
	if m != nil {
		return m.TicsPerBlock
	}
	return 0
}

func (m *Params) GetInputHistory() uint64 {
	if m != nil {
		return m.InputHistory
	}
	return 0
}

func (m *Params) GetController() string {
	if m != nil {
		return m.Controller
	}
	return ""
}

// GameState is the chain's view of the running game.
type GameState struct {
	// Tics executed so far. Also the index of the next input to be consumed.
	Tic uint64 `protobuf:"varint,1,opt,name=tic,proto3" json:"tic,omitempty"`
	// sha256 over the engine's linear memory after the last executed tic. This is
	// the commitment that makes a divergent replay show up as an apphash mismatch.
	StateHash []byte `protobuf:"bytes,2,opt,name=state_hash,json=stateHash,proto3" json:"state_hash,omitempty"`
	// Button mask most recently applied.
	Buttons uint32 `protobuf:"varint,3,opt,name=buttons,proto3" json:"buttons,omitempty"`
}

func (m *GameState) Reset()         { *m = GameState{} }
func (m *GameState) String() string { return proto.CompactTextString(m) }
func (*GameState) ProtoMessage()    {}
func (*GameState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d53e7c725f3a5c97, []int{1}
}
func (m *GameState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GameState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GameState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GameState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameState.Merge(m, src)
}
func (m *GameState) XXX_Size() int {
	return m.Size()
}
func (m *GameState) XXX_DiscardUnknown() {
	xxx_messageInfo_GameState.DiscardUnknown(m)
}

var xxx_messageInfo_GameState proto.InternalMessageInfo

func (m *GameState) GetTic() uint64 {
	if m != nil {
		return m.Tic
	}
	return 0
}

func (m *GameState) GetStateHash() []byte {
	if m != nil {
		return m.StateHash
	}
	return nil
}

func (m *GameState) GetButtons() uint32 {
	if m != nil {
		return m.Buttons
	}
	return 0
}

// Frame is the screen one tic drew.
//
// Frames are not consensus state: the engine re-derives them from the sim and
// the chain only commits to a hash of the sim. They are carried here so a
// client can watch every tic instead of only the last one of each block.
type Frame struct {
	// The tic that drew this screen.
	Tic uint64 `protobuf:"varint,1,opt,name=tic,proto3" json:"tic,omitempty"`
	// One palette index per pixel, row major.
	Pixels []byte `protobuf:"bytes,2,opt,name=pixels,proto3" json:"pixels,omitempty"`
	// 256 BGRA entries as of this tic.
	Palette []byte `protobuf:"bytes,3,opt,name=palette,proto3" json:"palette,omitempty"`
	// The block that drew it.
	BlockHeight int64 `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// That block's state commitment. It covers the block's last tic, so the
	// earlier tics of a block share the commitment that follows them.
	StateHash []byte    `protobuf:"bytes,5,opt,name=state_hash,json=stateHash,proto3" json:"state_hash,omitempty"`
	Time      time.Time `protobuf:"bytes,6,opt,name=time,proto3,stdtime" json:"time"`
}

func (m *Frame) Reset()         { *m = Frame{} }
func (m *Frame) String() string { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()    {}
func (*Frame) Descriptor() ([]byte, []int) {
	return fileDescriptor_d53e7c725f3a5c97, []int{2}
}
func (m *Frame) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Frame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Frame.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Frame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frame.Merge(m, src)
}
func (m *Frame) XXX_Size() int {
	return m.Size()
}
func (m *Frame) XXX_DiscardUnknown() {
	xxx_messageInfo_Frame.DiscardUnknown(m)
}

var xxx_messageInfo_Frame proto.InternalMessageInfo

func (m *Frame) GetTic() uint64 {
	if m != nil {
		return m.Tic
	}
	return 0
}

func (m *Frame) GetPixels() []byte {
	if m != nil {
		return m.Pixels
	}
	return nil
}

func (m *Frame) GetPalette() []byte {
	if m != nil {
		return m.Palette
	}
	return nil
}

func (m *Frame) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *Frame) GetStateHash() []byte {
	if m != nil {
		return m.StateHash
	}
	return nil
}

func (m *Frame) GetTime() time.Time {
	if m != nil {
		return m.Time
	}
	return time.Time{}
}

func init() {
	proto.RegisterEnum("gaia.doom.v1.Button", Button_name, Button_value)
	proto.RegisterType((*Params)(nil), "gaia.doom.v1.Params")
	proto.RegisterType((*GameState)(nil), "gaia.doom.v1.GameState")
	proto.RegisterType((*Frame)(nil), "gaia.doom.v1.Frame")
}

func init() { proto.RegisterFile("gaia/doom/v1/doom.proto", fileDescriptor_d53e7c725f3a5c97) }

var fileDescriptor_d53e7c725f3a5c97 = []byte{
	// 661 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xcd, 0x6e, 0xda, 0x4a,
	0x14, 0xc7, 0x71, 0x20, 0x24, 0x1c, 0x0c, 0x19, 0x26, 0x5f, 0x5c, 0xae, 0xae, 0xe1, 0x26, 0x5d,
	0xa0, 0x2c, 0xb0, 0x92, 0xf4, 0x4b, 0x91, 0xba, 0x80, 0xd4, 0x84, 0xa8, 0x2d, 0xa0, 0xc1, 0x28,
	0x6a, 0x55, 0xc9, 0x1a, 0x88, 0x0b, 0x56, 0x31, 0x63, 0xd9, 0x43, 0x3e, 0xde, 0xa0, 0xea, 0x2a,
	0x8f, 0x50, 0xa9, 0xcb, 0x6e, 0xfa, 0x08, 0xdd, 0x35, 0xcb, 0x2c, 0xbb, 0x6a, 0xab, 0x64, 0xd1,
	0x3e, 0x46, 0xe5, 0xb1, 0x91, 0x9c, 0xd0, 0x8d, 0x3d, 0xff, 0xdf, 0x9c, 0x39, 0xf3, 0x3f, 0xe7,
	0xd8, 0xb0, 0x3e, 0xa0, 0x16, 0x55, 0x8f, 0x19, 0xb3, 0xd5, 0x93, 0x6d, 0xf1, 0xae, 0x38, 0x2e,
	0xe3, 0x0c, 0xcb, 0xfe, 0x46, 0x45, 0x80, 0x93, 0xed, 0xc2, 0xca, 0x80, 0x0d, 0x98, 0xd8, 0x50,
	0xfd, 0x55, 0x10, 0x53, 0xc8, 0x51, 0xdb, 0x1a, 0x33, 0x55, 0x3c, 0x43, 0x54, 0x1c, 0x30, 0x36,
	0x18, 0x99, 0xaa, 0x50, 0xbd, 0xc9, 0x1b, 0x95, 0x5b, 0xb6, 0xe9, 0x71, 0x6a, 0x3b, 0x41, 0xc0,
	0xc6, 0x27, 0x09, 0x92, 0x6d, 0xea, 0x52, 0xdb, 0xc3, 0xff, 0xc0, 0xe2, 0x29, 0x3d, 0x36, 0x86,
	0xd4, 0x1b, 0xe6, 0xa5, 0x92, 0x54, 0x4e, 0x91, 0x85, 0x53, 0x7a, 0xdc, 0xa0, 0xde, 0x10, 0xdf,
	0x83, 0x2c, 0xb7, 0xfa, 0x9e, 0xe1, 0x98, 0xae, 0xd1, 0x1b, 0xb1, 0xfe, 0xdb, 0xfc, 0x5c, 0x49,
	0x2a, 0x67, 0x88, 0xec, 0xd3, 0xb6, 0xe9, 0xd6, 0x7c, 0x86, 0x37, 0x21, 0x63, 0x8d, 0x9d, 0x09,
	0x37, 0x86, 0x96, 0xc7, 0x99, 0x7b, 0x9e, 0x8f, 0x97, 0xa4, 0x72, 0x82, 0xc8, 0x02, 0x36, 0x02,
	0x86, 0x15, 0x80, 0x3e, 0x1b, 0x73, 0x97, 0x8d, 0x46, 0xa6, 0x9b, 0x4f, 0x88, 0x7b, 0x22, 0x64,
	0xef, 0xdf, 0xdf, 0x1f, 0x8a, 0xd2, 0xfb, 0x5f, 0x9f, 0xb7, 0xb0, 0x68, 0xc5, 0x59, 0xd0, 0x8c,
	0xc0, 0xe2, 0xc6, 0x6b, 0x48, 0x1d, 0x50, 0xdb, 0xec, 0x70, 0xca, 0x4d, 0x8c, 0x20, 0xce, 0xad,
	0xbe, 0xb0, 0x9a, 0x20, 0xfe, 0x12, 0xff, 0x07, 0xe0, 0xf9, 0x5b, 0x41, 0x0d, 0xbe, 0x45, 0x99,
	0xa4, 0x04, 0x11, 0x55, 0xe4, 0x61, 0xa1, 0x37, 0xe1, 0x9c, 0x8d, 0x3d, 0xe1, 0x2c, 0x43, 0xa6,
	0x72, 0x2f, 0xe1, 0x5f, 0xba, 0xf1, 0x55, 0x82, 0xf9, 0xba, 0x4b, 0xed, 0xbf, 0xa5, 0x5e, 0x83,
	0xa4, 0x63, 0x9d, 0x99, 0x23, 0x2f, 0x4c, 0x1b, 0x2a, 0x3f, 0xa7, 0x43, 0x47, 0x26, 0xe7, 0xa6,
	0xc8, 0x29, 0x93, 0xa9, 0xc4, 0xff, 0x83, 0x2c, 0x5a, 0x65, 0x0c, 0x4d, 0x6b, 0x30, 0xe4, 0xa2,
	0xd4, 0x38, 0x49, 0x0b, 0xd6, 0x10, 0xe8, 0x8e, 0xdf, 0xf9, 0xbb, 0x7e, 0x1f, 0x43, 0xc2, 0x1f,
	0x57, 0x3e, 0x59, 0x92, 0xca, 0xe9, 0x9d, 0x42, 0x25, 0x98, 0x65, 0x65, 0x3a, 0xcb, 0x8a, 0x3e,
	0x9d, 0x65, 0x6d, 0xf1, 0xf2, 0x7b, 0x31, 0x76, 0xf1, 0xa3, 0x28, 0x11, 0x71, 0x62, 0xeb, 0x4b,
	0x1c, 0x92, 0x35, 0x51, 0x1b, 0xc6, 0x90, 0xad, 0x75, 0x75, 0xbd, 0xd5, 0x34, 0xea, 0x2d, 0x72,
	0x54, 0x25, 0x4f, 0x51, 0x0c, 0x2f, 0xc3, 0x52, 0xc8, 0x6a, 0xd5, 0xfd, 0x67, 0x02, 0x4a, 0x78,
	0x05, 0x50, 0x08, 0xf5, 0x2e, 0x69, 0x1a, 0xcf, 0xb5, 0xba, 0x8e, 0xe6, 0xf0, 0x2a, 0xe4, 0xa2,
	0x94, 0x1c, 0x1e, 0x34, 0x74, 0x14, 0xc7, 0x6b, 0x80, 0x43, 0xdc, 0xd1, 0x49, 0xb5, 0xae, 0x05,
	0xe1, 0x09, 0xbc, 0x0e, 0xcb, 0xb7, 0x79, 0x70, 0x60, 0x1e, 0x2f, 0x41, 0x7a, 0x6a, 0xe3, 0x90,
	0x68, 0x28, 0x89, 0xb3, 0x00, 0x21, 0xe8, 0x76, 0x34, 0xb4, 0x10, 0xd1, 0xa4, 0xdb, 0x44, 0x8b,
	0x38, 0x07, 0x99, 0x5b, 0x99, 0x50, 0x2a, 0x82, 0xb4, 0xce, 0x7e, 0xb5, 0xad, 0x21, 0xc0, 0x08,
	0xe4, 0x29, 0x6a, 0xea, 0x1a, 0x41, 0xe9, 0x48, 0x9e, 0x17, 0xd5, 0x36, 0x92, 0x23, 0xfa, 0xa5,
	0xd6, 0x41, 0x19, 0x9c, 0x81, 0x54, 0xa8, 0x9b, 0x2d, 0x94, 0x8d, 0xb4, 0xe2, 0x48, 0xab, 0xb6,
	0x5b, 0x4d, 0x63, 0x1b, 0x2d, 0xcd, 0xc2, 0x1d, 0x84, 0x66, 0xe1, 0x2e, 0xca, 0xcd, 0xc2, 0xfb,
	0x08, 0xcf, 0xc2, 0x07, 0x68, 0x79, 0x16, 0x3e, 0x44, 0x2b, 0xb3, 0xf0, 0x11, 0x5a, 0x2d, 0x24,
	0xde, 0x7d, 0x54, 0x62, 0xb5, 0x27, 0x97, 0xd7, 0x8a, 0x74, 0x75, 0xad, 0x48, 0x3f, 0xaf, 0x15,
	0xe9, 0xe2, 0x46, 0x89, 0x5d, 0xdd, 0x28, 0xb1, 0x6f, 0x37, 0x4a, 0xec, 0xd5, 0xe6, 0xc0, 0xe2,
	0xc3, 0x49, 0xaf, 0xd2, 0x67, 0xb6, 0xda, 0x67, 0x9e, 0xcd, 0x3c, 0x35, 0xfa, 0xab, 0xf0, 0x73,
	0xc7, 0xf4, 0x7a, 0x49, 0xf1, 0x95, 0xec, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x6a, 0xfd, 0x5e,
	0x37, 0x51, 0x04, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.WadHash != that1.WadHash {
		return false
	}
	if this.TicsPerBlock != that1.TicsPerBlock {
		return false
	}
	if this.InputHistory != that1.InputHistory {
		return false
	}
	if this.Controller != that1.Controller {
		return false
	}
	return true
}
func (this *GameState) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GameState)
	if !ok {
		that2, ok := that.(GameState)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Tic != that1.Tic {
		return false
	}
	if !bytes.Equal(this.StateHash, that1.StateHash) {
		return false
	}
	if this.Buttons != that1.Buttons {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Controller) > 0 {
		i -= len(m.Controller)
		copy(dAtA[i:], m.Controller)
		i = encodeVarintDoom(dAtA, i, uint64(len(m.Controller)))
		i--
		dAtA[i] = 0x22
	}
	if m.InputHistory != 0 {
		i = encodeVarintDoom(dAtA, i, uint64(m.InputHistory))
		i--
		dAtA[i] = 0x18
	}
	if m.TicsPerBlock != 0 {
		i = encodeVarintDoom(dAtA, i, uint64(m.TicsPerBlock))
		i--
		dAtA[i] = 0x10
	}
	if len(m.WadHash) > 0 {
		i -= len(m.WadHash)
		copy(dAtA[i:], m.WadHash)
		i = encodeVarintDoom(dAtA, i, uint64(len(m.WadHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GameState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GameState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GameState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Buttons != 0 {
		i = encodeVarintDoom(dAtA, i, uint64(m.Buttons))
		i--
		dAtA[i] = 0x18
	}
	if len(m.StateHash) > 0 {
		i -= len(m.StateHash)
		copy(dAtA[i:], m.StateHash)
		i = encodeVarintDoom(dAtA, i, uint64(len(m.StateHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.Tic != 0 {
		i = encodeVarintDoom(dAtA, i, uint64(m.Tic))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Frame) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Frame) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Frame) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.Time, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Time):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintDoom(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x32
	if len(m.StateHash) > 0 {
		i -= len(m.StateHash)
		copy(dAtA[i:], m.StateHash)
		i = encodeVarintDoom(dAtA, i, uint64(len(m.StateHash)))
		i--
		dAtA[i] = 0x2a
	}
	if m.BlockHeight != 0 {
		i = encodeVarintDoom(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Palette) > 0 {
		i -= len(m.Palette)
		copy(dAtA[i:], m.Palette)
		i = encodeVarintDoom(dAtA, i, uint64(len(m.Palette)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Pixels) > 0 {
		i -= len(m.Pixels)
		copy(dAtA[i:], m.Pixels)
		i = encodeVarintDoom(dAtA, i, uint64(len(m.Pixels)))
		i--
		dAtA[i] = 0x12
	}
	if m.Tic != 0 {
		i = encodeVarintDoom(dAtA, i, uint64(m.Tic))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintDoom(dAtA []byte, offset int, v uint64) int {
	offset -= sovDoom(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.WadHash)
	if l > 0 {
		n += 1 + l + sovDoom(uint64(l))
	}
	if m.TicsPerBlock != 0 {
		n += 1 + sovDoom(uint64(m.TicsPerBlock))
	}
	if m.InputHistory != 0 {
		n += 1 + sovDoom(uint64(m.InputHistory))
	}
	l = len(m.Controller)
	if l > 0 {
		n += 1 + l + sovDoom(uint64(l))
	}
	return n
}

func (m *GameState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Tic != 0 {
		n += 1 + sovDoom(uint64(m.Tic))
	}
	l = len(m.StateHash)
	if l > 0 {
		n += 1 + l + sovDoom(uint64(l))
	}
	if m.Buttons != 0 {
		n += 1 + sovDoom(uint64(m.Buttons))
	}
	return n
}

func (m *Frame) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Tic != 0 {
		n += 1 + sovDoom(uint64(m.Tic))
	}
	l = len(m.Pixels)
	if l > 0 {
		n += 1 + l + sovDoom(uint64(l))
	}
	l = len(m.Palette)
	if l > 0 {
		n += 1 + l + sovDoom(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovDoom(uint64(m.BlockHeight))
	}
	l = len(m.StateHash)
	if l > 0 {
		n += 1 + l + sovDoom(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Time)
	n += 1 + l + sovDoom(uint64(l))
	return n
}

func sovDoom(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDoom(x uint64) (n int) {
	return sovDoom(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDoom
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WadHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDoom
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDoom
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDoom
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WadHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TicsPerBlock", wireType)
			}
			m.TicsPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDoom
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TicsPerBlock |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InputHistory", wireType)
			}
			m.InputHistory = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDoom
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InputHistory |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Controller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDoom
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDoom
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDoom
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Controller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDoom(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDoom
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GameState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDoom
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GameState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GameState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tic", wireType)
			}
			m.Tic = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDoom
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tic |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDoom
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDoom
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDoom
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateHash = append(m.StateHash[:0], dAtA[iNdEx:postIndex]...)
			if m.StateHash == nil {
				m.StateHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buttons", wireType)
			}
			m.Buttons = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDoom
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Buttons |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDoom(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDoom
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Frame) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDoom
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Frame: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Frame: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tic", wireType)
			}
			m.Tic = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDoom
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tic |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pixels", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDoom
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDoom
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDoom
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pixels = append(m.Pixels[:0], dAtA[iNdEx:postIndex]...)
			if m.Pixels == nil {
				m.Pixels = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Palette", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDoom
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDoom
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDoom
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Palette = append(m.Palette[:0], dAtA[iNdEx:postIndex]...)
			if m.Palette == nil {
				m.Palette = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDoom
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDoom
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDoom
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDoom
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateHash = append(m.StateHash[:0], dAtA[iNdEx:postIndex]...)
			if m.StateHash == nil {
				m.StateHash = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDoom
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDoom
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDoom
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.Time, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDoom(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDoom
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDoom(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDoom
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDoom
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDoom
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDoom
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDoom
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDoom
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDoom        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDoom          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDoom = fmt.Errorf("proto: unexpected end of group")
)
