// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gaia/doom/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgInput holds down a set of buttons.
//
// One of these per tic is what playing the game looks like: a client sends
// roughly 35 a second and the EndBlocker feeds the last one it saw to the
// engine. A tic with no input is a released-keys tic, same as a dropped packet
// in a vanilla netgame.
type MsgInput struct {
	Player string `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	// Bit mask of Button values.
	Buttons uint32 `protobuf:"varint,2,opt,name=buttons,proto3" json:"buttons,omitempty"`
}

func (m *MsgInput) Reset()         { *m = MsgInput{} }
func (m *MsgInput) String() string { return proto.CompactTextString(m) }
func (*MsgInput) ProtoMessage()    {}
func (*MsgInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_0846e799e6651ee5, []int{0}
}
func (m *MsgInput) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInput.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInput.Merge(m, src)
}
func (m *MsgInput) XXX_Size() int {
	return m.Size()
}
func (m *MsgInput) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInput.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInput proto.InternalMessageInfo

func (m *MsgInput) GetPlayer() string {
	if m != nil {
		return m.Player
	}
	return ""
}

func (m *MsgInput) GetButtons() uint32 {
	if m != nil {
		return m.Buttons
	}
	return 0
}

type MsgInputResponse struct {
	// Tic this input is expected to land on.
	Tic uint64 `protobuf:"varint,1,opt,name=tic,proto3" json:"tic,omitempty"`
}

func (m *MsgInputResponse) Reset()         { *m = MsgInputResponse{} }
func (m *MsgInputResponse) String() string { return proto.CompactTextString(m) }
func (*MsgInputResponse) ProtoMessage()    {}
func (*MsgInputResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0846e799e6651ee5, []int{1}
}
func (m *MsgInputResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInputResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInputResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInputResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInputResponse.Merge(m, src)
}
func (m *MsgInputResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgInputResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInputResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInputResponse proto.InternalMessageInfo

func (m *MsgInputResponse) GetTic() uint64 {
	if m != nil {
		return m.Tic
	}
	return 0
}

// MsgFrame carries one screen.
//
// Only the last tic of a block can be checked, because that is the only frame
// the engine still holds when the next block's transactions run. Intermediate
// tics are gone by then, so this pushes one frame per block and a client
// reading blocks sees the game at the block rate rather than at 35Hz.
type MsgFrame struct {
	Submitter string `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	// The tic this screen was drawn by. It has to be the tic the chain is
	// sitting on, so a frame that misses its block is rejected rather than
	// shown late.
	Tic uint64 `protobuf:"varint,2,opt,name=tic,proto3" json:"tic,omitempty"`
	// Palette indices, run length encoded. A DOOM screen is mostly flat runs, so
	// this is worth roughly 3x and the block data is the whole cost here.
	Pixels []byte `protobuf:"bytes,3,opt,name=pixels,proto3" json:"pixels,omitempty"`
	// 256 BGRA entries, uncompressed.
	Palette []byte `protobuf:"bytes,4,opt,name=palette,proto3" json:"palette,omitempty"`
}

func (m *MsgFrame) Reset()         { *m = MsgFrame{} }
func (m *MsgFrame) String() string { return proto.CompactTextString(m) }
func (*MsgFrame) ProtoMessage()    {}
func (*MsgFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_0846e799e6651ee5, []int{2}
}
func (m *MsgFrame) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFrame.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFrame.Merge(m, src)
}
func (m *MsgFrame) XXX_Size() int {
	return m.Size()
}
func (m *MsgFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFrame.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFrame proto.InternalMessageInfo

func (m *MsgFrame) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *MsgFrame) GetTic() uint64 {
	if m != nil {
		return m.Tic
	}
	return 0
}

func (m *MsgFrame) GetPixels() []byte {
	if m != nil {
		return m.Pixels
	}
	return nil
}

func (m *MsgFrame) GetPalette() []byte {
	if m != nil {
		return m.Palette
	}
	return nil
}

type MsgFrameResponse struct {
	// How many bytes of block data the frame cost, so a client can see the bill.
	BlockBytes uint64 `protobuf:"varint,1,opt,name=block_bytes,json=blockBytes,proto3" json:"block_bytes,omitempty"`
}

func (m *MsgFrameResponse) Reset()         { *m = MsgFrameResponse{} }
func (m *MsgFrameResponse) String() string { return proto.CompactTextString(m) }
func (*MsgFrameResponse) ProtoMessage()    {}
func (*MsgFrameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0846e799e6651ee5, []int{3}
}
func (m *MsgFrameResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFrameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFrameResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFrameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFrameResponse.Merge(m, src)
}
func (m *MsgFrameResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgFrameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFrameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFrameResponse proto.InternalMessageInfo

func (m *MsgFrameResponse) GetBlockBytes() uint64 {
	if m != nil {
		return m.BlockBytes
	}
	return 0
}

type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless
	// overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params defines the x/doom parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_0846e799e6651ee5, []int{4}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0846e799e6651ee5, []int{5}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgInput)(nil), "gaia.doom.v1.MsgInput")
	proto.RegisterType((*MsgInputResponse)(nil), "gaia.doom.v1.MsgInputResponse")
	proto.RegisterType((*MsgFrame)(nil), "gaia.doom.v1.MsgFrame")
	proto.RegisterType((*MsgFrameResponse)(nil), "gaia.doom.v1.MsgFrameResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "gaia.doom.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "gaia.doom.v1.MsgUpdateParamsResponse")
}

func init() { proto.RegisterFile("gaia/doom/v1/tx.proto", fileDescriptor_0846e799e6651ee5) }

var fileDescriptor_0846e799e6651ee5 = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcf, 0x8b, 0xd3, 0x40,
	0x18, 0xed, 0x6c, 0xb7, 0xd5, 0xce, 0x56, 0x5c, 0x43, 0xdd, 0x4d, 0x0b, 0xa6, 0x25, 0xfe, 0xa0,
	0x16, 0x4d, 0xdc, 0x5d, 0x50, 0x28, 0xc8, 0x62, 0x0f, 0x82, 0x87, 0x82, 0x44, 0xbd, 0x78, 0x59,
	0x26, 0xed, 0x30, 0x1b, 0x6c, 0x32, 0x21, 0x33, 0x59, 0xda, 0x8b, 0x88, 0x47, 0x4f, 0xfe, 0x09,
	0x1e, 0x3d, 0x56, 0xf0, 0x8f, 0xd8, 0xe3, 0xe2, 0xc9, 0x93, 0x48, 0x2b, 0xd4, 0x3f, 0x43, 0x66,
	0x92, 0x49, 0x1b, 0xbb, 0xe8, 0x5e, 0xc2, 0xf7, 0xbd, 0xef, 0xf1, 0xe6, 0xbd, 0x2f, 0x33, 0xf0,
	0x3a, 0x41, 0x1e, 0xb2, 0x87, 0x94, 0xfa, 0xf6, 0xc9, 0x9e, 0xcd, 0xc7, 0x56, 0x18, 0x51, 0x4e,
	0xb5, 0xaa, 0x80, 0x2d, 0x01, 0x5b, 0x27, 0x7b, 0x8d, 0x1a, 0xa1, 0x84, 0xca, 0x81, 0x2d, 0xaa,
	0x84, 0xd3, 0xb8, 0x86, 0x7c, 0x2f, 0xa0, 0xb6, 0xfc, 0xa6, 0x50, 0x7d, 0x40, 0x99, 0x4f, 0xd9,
	0x51, 0xc2, 0x4d, 0x9a, 0x74, 0xb4, 0x9b, 0x74, 0xb6, 0xcf, 0x88, 0x38, 0xc9, 0x67, 0x44, 0x0d,
	0x72, 0x0e, 0xe4, 0x91, 0x72, 0x60, 0xbe, 0x85, 0x97, 0xfb, 0x8c, 0x3c, 0x0b, 0xc2, 0x98, 0x6b,
	0x0f, 0x60, 0x39, 0x1c, 0xa1, 0x09, 0x8e, 0x74, 0xd0, 0x02, 0xed, 0x4a, 0x4f, 0xff, 0xf6, 0xf5,
	0x7e, 0x2d, 0xd5, 0x7f, 0x32, 0x1c, 0x46, 0x98, 0xb1, 0x17, 0x3c, 0xf2, 0x02, 0xe2, 0xa4, 0x3c,
	0x4d, 0x87, 0x97, 0xdc, 0x98, 0x73, 0x1a, 0x30, 0x7d, 0xa3, 0x05, 0xda, 0x57, 0x1c, 0xd5, 0x76,
	0xef, 0xfc, 0xfe, 0xd4, 0x2c, 0xbc, 0x5f, 0x4c, 0x3b, 0x29, 0xf5, 0xc3, 0x62, 0xda, 0xd1, 0x96,
	0x26, 0xd4, 0x99, 0xe6, 0x2d, 0xb8, 0xad, 0x6a, 0x07, 0xb3, 0x90, 0x06, 0x0c, 0x6b, 0xdb, 0xb0,
	0xc8, 0xbd, 0x81, 0x34, 0xb1, 0xe9, 0x88, 0xd2, 0xfc, 0x02, 0xa4, 0xcd, 0xa7, 0x11, 0xf2, 0xb1,
	0xf6, 0x10, 0x56, 0x58, 0xec, 0xfa, 0x1e, 0xe7, 0x17, 0x70, 0xba, 0xa4, 0x2a, 0xd9, 0x8d, 0x4c,
	0x56, 0xdb, 0x81, 0xe5, 0xd0, 0x1b, 0xe3, 0x11, 0xd3, 0x8b, 0x2d, 0xd0, 0xae, 0x3a, 0x69, 0x27,
	0x62, 0x85, 0x68, 0x84, 0x39, 0xc7, 0xfa, 0xa6, 0x1c, 0xa8, 0xb6, 0x7b, 0x57, 0xc5, 0x5a, 0xea,
	0xae, 0x27, 0x93, 0x36, 0xcd, 0x03, 0x99, 0x4c, 0xd6, 0x59, 0xb2, 0x26, 0xdc, 0x72, 0x47, 0x74,
	0xf0, 0xe6, 0xc8, 0x9d, 0x70, 0xcc, 0xd2, 0x84, 0x50, 0x42, 0x3d, 0x81, 0x98, 0x53, 0x00, 0xaf,
	0xf6, 0x19, 0x79, 0x15, 0x0e, 0x11, 0xc7, 0xcf, 0x51, 0x84, 0x7c, 0x26, 0xf2, 0xa2, 0x98, 0x1f,
	0xd3, 0xc8, 0xe3, 0x93, 0xff, 0xe7, 0xcd, 0xa8, 0xda, 0x23, 0x58, 0x0e, 0xa5, 0x82, 0x8c, 0xbc,
	0xb5, 0x5f, 0xb3, 0x56, 0xef, 0x9b, 0x95, 0xa8, 0xf7, 0x2a, 0xa7, 0x3f, 0x9a, 0x85, 0xcf, 0x8b,
	0x69, 0x07, 0x38, 0x29, 0xbd, 0x7b, 0x4f, 0x06, 0xcc, 0x84, 0x44, 0xc0, 0x7a, 0x2e, 0xe0, 0xaa,
	0x3d, 0xb3, 0x0e, 0x77, 0xff, 0x82, 0x54, 0xdc, 0xfd, 0x5f, 0x00, 0x16, 0xfb, 0x8c, 0x68, 0x87,
	0xb0, 0x94, 0xdc, 0xb0, 0x9d, 0xbc, 0x05, 0xf5, 0xe7, 0x1b, 0xc6, 0xf9, 0x78, 0xb6, 0xb7, 0x43,
	0x58, 0x4a, 0xfe, 0xfd, 0xba, 0x80, 0xc4, 0xcf, 0x11, 0xc8, 0x2f, 0xfe, 0x25, 0xac, 0xe6, 0x76,
	0x7a, 0x63, 0x8d, 0xbf, 0x3a, 0x6e, 0xdc, 0xfe, 0xe7, 0x58, 0xa9, 0x36, 0x4a, 0xef, 0xc4, 0xde,
	0x7a, 0x8f, 0x4f, 0x67, 0x06, 0x38, 0x9b, 0x19, 0xe0, 0xe7, 0xcc, 0x00, 0x1f, 0xe7, 0x46, 0xe1,
	0x6c, 0x6e, 0x14, 0xbe, 0xcf, 0x8d, 0xc2, 0xeb, 0x9b, 0xc4, 0xe3, 0xc7, 0xb1, 0x6b, 0x0d, 0xa8,
	0x9f, 0x3e, 0x54, 0x5b, 0x2e, 0x72, 0x9c, 0xac, 0x92, 0x4f, 0x42, 0xcc, 0xdc, 0xb2, 0x7c, 0x89,
	0x07, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xac, 0xa3, 0xc5, 0x53, 0x26, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Input sets the buttons held down for the tics run by the block it lands in.
	Input(ctx context.Context, in *MsgInput, opts ...grpc.CallOption) (*MsgInputResponse, error)
	// Frame pushes a rendered screen into block data.
	//
	// It buys nothing a client could not derive for itself, which is the point:
	// it is what watching the game entirely out of the blocks costs. The handler
	// only accepts a frame that matches what the engine already drew, so the
	// bytes are redundant by construction and a node cannot smuggle a picture
	// the sim never produced.
	Frame(ctx context.Context, in *MsgFrame, opts ...grpc.CallOption) (*MsgFrameResponse, error)
	// UpdateParams updates the x/doom module parameters.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Input(ctx context.Context, in *MsgInput, opts ...grpc.CallOption) (*MsgInputResponse, error) {
	out := new(MsgInputResponse)
	err := c.cc.Invoke(ctx, "/gaia.doom.v1.Msg/Input", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Frame(ctx context.Context, in *MsgFrame, opts ...grpc.CallOption) (*MsgFrameResponse, error) {
	out := new(MsgFrameResponse)
	err := c.cc.Invoke(ctx, "/gaia.doom.v1.Msg/Frame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/gaia.doom.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Input sets the buttons held down for the tics run by the block it lands in.
	Input(context.Context, *MsgInput) (*MsgInputResponse, error)
	// Frame pushes a rendered screen into block data.
	//
	// It buys nothing a client could not derive for itself, which is the point:
	// it is what watching the game entirely out of the blocks costs. The handler
	// only accepts a frame that matches what the engine already drew, so the
	// bytes are redundant by construction and a node cannot smuggle a picture
	// the sim never produced.
	Frame(context.Context, *MsgFrame) (*MsgFrameResponse, error)
	// UpdateParams updates the x/doom module parameters.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Input(ctx context.Context, req *MsgInput) (*MsgInputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Input not implemented")
}
func (*UnimplementedMsgServer) Frame(ctx context.Context, req *MsgFrame) (*MsgFrameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Frame not implemented")
}
func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Input_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Input(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gaia.doom.v1.Msg/Input",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Input(ctx, req.(*MsgInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Frame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFrame)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Frame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gaia.doom.v1.Msg/Frame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Frame(ctx, req.(*MsgFrame))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gaia.doom.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gaia.doom.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Input",
			Handler:    _Msg_Input_Handler,
		},
		{
			MethodName: "Frame",
			Handler:    _Msg_Frame_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gaia/doom/v1/tx.proto",
}

func (m *MsgInput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInput) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInput) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Buttons != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Buttons))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Player) > 0 {
		i -= len(m.Player)
		copy(dAtA[i:], m.Player)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Player)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgInputResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInputResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInputResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Tic != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Tic))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgFrame) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFrame) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFrame) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Palette) > 0 {
		i -= len(m.Palette)
		copy(dAtA[i:], m.Palette)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Palette)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Pixels) > 0 {
		i -= len(m.Pixels)
		copy(dAtA[i:], m.Pixels)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Pixels)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Tic != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Tic))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Submitter) > 0 {
		i -= len(m.Submitter)
		copy(dAtA[i:], m.Submitter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Submitter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgFrameResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFrameResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFrameResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockBytes != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BlockBytes))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgInput) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Player)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Buttons != 0 {
		n += 1 + sovTx(uint64(m.Buttons))
	}
	return n
}

func (m *MsgInputResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Tic != 0 {
		n += 1 + sovTx(uint64(m.Tic))
	}
	return n
}

func (m *MsgFrame) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Submitter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Tic != 0 {
		n += 1 + sovTx(uint64(m.Tic))
	}
	l = len(m.Pixels)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Palette)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgFrameResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockBytes != 0 {
		n += 1 + sovTx(uint64(m.BlockBytes))
	}
	return n
}

func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgInput) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Player", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Player = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buttons", wireType)
			}
			m.Buttons = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Buttons |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInputResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInputResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInputResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tic", wireType)
			}
			m.Tic = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tic |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFrame) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFrame: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFrame: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submitter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tic", wireType)
			}
			m.Tic = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tic |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pixels", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pixels = append(m.Pixels[:0], dAtA[iNdEx:postIndex]...)
			if m.Pixels == nil {
				m.Pixels = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Palette", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Palette = append(m.Palette[:0], dAtA[iNdEx:postIndex]...)
			if m.Palette == nil {
				m.Palette = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFrameResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFrameResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFrameResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockBytes", wireType)
			}
			m.BlockBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockBytes |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
