// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gaia/mc/v1/mc.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params configures the world.
type Params struct {
	// TicksPerBlock is how many game ticks a block advances the world by.
	// Minecraft wants 20 a second, so this is set against the block rate the
	// chain actually manages.
	TicksPerBlock uint32 `protobuf:"varint,1,opt,name=ticks_per_block,json=ticksPerBlock,proto3" json:"ticks_per_block,omitempty"`
	// Controller is the only address allowed to play. Empty means anyone, which
	// on a single player world means whoever gets a transaction in first.
	Controller string `protobuf:"bytes,2,opt,name=controller,proto3" json:"controller,omitempty"`
	// GroundLevel is the Y of the topmost solid layer of the superflat world.
	// Everything above it is air and everything below is stone.
	GroundLevel int32 `protobuf:"varint,3,opt,name=ground_level,json=groundLevel,proto3" json:"ground_level,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c15964ef051280e, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetTicksPerBlock() uint32 {
	if m != nil {
		return m.TicksPerBlock
	}
	return 0
}

func (m *Params) GetController() string {
	if m != nil {
		return m.Controller
	}
	return ""
}

func (m *Params) GetGroundLevel() int32 {
	if m != nil {
		return m.GroundLevel
	}
	return 0
}

// GameState is the world clock and its commitment.
type GameState struct {
	// Tick the world is sitting on. Height N is tick N * ticks_per_block.
	Tick uint64 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	// StateHash commits to the whole world: the player, every block edit and the
	// tick. A node that replayed the log differently fails the apphash.
	StateHash []byte `protobuf:"bytes,2,opt,name=state_hash,json=stateHash,proto3" json:"state_hash,omitempty"`
}

func (m *GameState) Reset()         { *m = GameState{} }
func (m *GameState) String() string { return proto.CompactTextString(m) }
func (*GameState) ProtoMessage()    {}
func (*GameState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c15964ef051280e, []int{1}
}
func (m *GameState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GameState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GameState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GameState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameState.Merge(m, src)
}
func (m *GameState) XXX_Size() int {
	return m.Size()
}
func (m *GameState) XXX_DiscardUnknown() {
	xxx_messageInfo_GameState.DiscardUnknown(m)
}

var xxx_messageInfo_GameState proto.InternalMessageInfo

func (m *GameState) GetTick() uint64 {
	if m != nil {
		return m.Tick
	}
	return 0
}

func (m *GameState) GetStateHash() []byte {
	if m != nil {
		return m.StateHash
	}
	return nil
}

// Player is where the player is and what it is holding.
//
// Positions are fixed point in 1/4096 of a block and angles in 1/100 of a
// degree. Nothing in consensus touches a float, because Go is allowed to fuse
// a multiply-add on some architectures and not others, which would fork the
// chain across validator hardware.
type Player struct {
	// Address that owns the seat. Empty until someone joins.
	Address  string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	X        int64  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y        int64  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Z        int64  `protobuf:"varint,4,opt,name=z,proto3" json:"z,omitempty"`
	Yaw      int32  `protobuf:"varint,5,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch    int32  `protobuf:"varint,6,opt,name=pitch,proto3" json:"pitch,omitempty"`
	OnGround bool   `protobuf:"varint,7,opt,name=on_ground,json=onGround,proto3" json:"on_ground,omitempty"`
	// Hotbar slot 0-8, which is what the next Place puts down.
	Hotbar uint32 `protobuf:"varint,8,opt,name=hotbar,proto3" json:"hotbar,omitempty"`
	// Joined is false before the first transaction, so a fresh world knows to
	// spawn the player rather than restore it.
	Joined bool `protobuf:"varint,9,opt,name=joined,proto3" json:"joined,omitempty"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c15964ef051280e, []int{2}
}
func (m *Player) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Player.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return m.Size()
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Player) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Player) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Player) GetZ() int64 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *Player) GetYaw() int32 {
	if m != nil {
		return m.Yaw
	}
	return 0
}

func (m *Player) GetPitch() int32 {
	if m != nil {
		return m.Pitch
	}
	return 0
}

func (m *Player) GetOnGround() bool {
	if m != nil {
		return m.OnGround
	}
	return false
}

func (m *Player) GetHotbar() uint32 {
	if m != nil {
		return m.Hotbar
	}
	return 0
}

func (m *Player) GetJoined() bool {
	if m != nil {
		return m.Joined
	}
	return false
}

// BlockPos is a block coordinate.
type BlockPos struct {
	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Z int32 `protobuf:"varint,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (m *BlockPos) Reset()         { *m = BlockPos{} }
func (m *BlockPos) String() string { return proto.CompactTextString(m) }
func (*BlockPos) ProtoMessage()    {}
func (*BlockPos) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c15964ef051280e, []int{3}
}
func (m *BlockPos) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BlockPos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BlockPos.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BlockPos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockPos.Merge(m, src)
}
func (m *BlockPos) XXX_Size() int {
	return m.Size()
}
func (m *BlockPos) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockPos.DiscardUnknown(m)
}

var xxx_messageInfo_BlockPos proto.InternalMessageInfo

func (m *BlockPos) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *BlockPos) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *BlockPos) GetZ() int32 {
	if m != nil {
		return m.Z
	}
	return 0
}

// Move is a position report.
//
// Minecraft's movement has always been client authoritative, so this is the
// client saying where it is rather than the server deciding. The chain records
// it; nothing here simulates physics.
type Move struct {
	X        int64 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y        int64 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Z        int64 `protobuf:"varint,3,opt,name=z,proto3" json:"z,omitempty"`
	Yaw      int32 `protobuf:"varint,4,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch    int32 `protobuf:"varint,5,opt,name=pitch,proto3" json:"pitch,omitempty"`
	OnGround bool  `protobuf:"varint,6,opt,name=on_ground,json=onGround,proto3" json:"on_ground,omitempty"`
}

func (m *Move) Reset()         { *m = Move{} }
func (m *Move) String() string { return proto.CompactTextString(m) }
func (*Move) ProtoMessage()    {}
func (*Move) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c15964ef051280e, []int{4}
}
func (m *Move) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Move) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Move.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Move) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Move.Merge(m, src)
}
func (m *Move) XXX_Size() int {
	return m.Size()
}
func (m *Move) XXX_DiscardUnknown() {
	xxx_messageInfo_Move.DiscardUnknown(m)
}

var xxx_messageInfo_Move proto.InternalMessageInfo

func (m *Move) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Move) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Move) GetZ() int64 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *Move) GetYaw() int32 {
	if m != nil {
		return m.Yaw
	}
	return 0
}

func (m *Move) GetPitch() int32 {
	if m != nil {
		return m.Pitch
	}
	return 0
}

func (m *Move) GetOnGround() bool {
	if m != nil {
		return m.OnGround
	}
	return false
}

// Dig removes a block.
type Dig struct {
	Pos BlockPos `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos"`
}

func (m *Dig) Reset()         { *m = Dig{} }
func (m *Dig) String() string { return proto.CompactTextString(m) }
func (*Dig) ProtoMessage()    {}
func (*Dig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c15964ef051280e, []int{5}
}
func (m *Dig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Dig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Dig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Dig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dig.Merge(m, src)
}
func (m *Dig) XXX_Size() int {
	return m.Size()
}
func (m *Dig) XXX_DiscardUnknown() {
	xxx_messageInfo_Dig.DiscardUnknown(m)
}

var xxx_messageInfo_Dig proto.InternalMessageInfo

func (m *Dig) GetPos() BlockPos {
	if m != nil {
		return m.Pos
	}
	return BlockPos{}
}

// Place puts a block down.
type Place struct {
	Pos BlockPos `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos"`
	// State is a global palette block state id, the same numbering the client
	// uses on the wire. The gateway resolves it from the held item.
	State uint32 `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (m *Place) Reset()         { *m = Place{} }
func (m *Place) String() string { return proto.CompactTextString(m) }
func (*Place) ProtoMessage()    {}
func (*Place) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c15964ef051280e, []int{6}
}
func (m *Place) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Place) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Place.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Place) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Place.Merge(m, src)
}
func (m *Place) XXX_Size() int {
	return m.Size()
}
func (m *Place) XXX_DiscardUnknown() {
	xxx_messageInfo_Place.DiscardUnknown(m)
}

var xxx_messageInfo_Place proto.InternalMessageInfo

func (m *Place) GetPos() BlockPos {
	if m != nil {
		return m.Pos
	}
	return BlockPos{}
}

func (m *Place) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

// Chat is a line the player typed.
type Chat struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (m *Chat) Reset()         { *m = Chat{} }
func (m *Chat) String() string { return proto.CompactTextString(m) }
func (*Chat) ProtoMessage()    {}
func (*Chat) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c15964ef051280e, []int{7}
}
func (m *Chat) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Chat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Chat.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Chat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chat.Merge(m, src)
}
func (m *Chat) XXX_Size() int {
	return m.Size()
}
func (m *Chat) XXX_DiscardUnknown() {
	xxx_messageInfo_Chat.DiscardUnknown(m)
}

var xxx_messageInfo_Chat proto.InternalMessageInfo

func (m *Chat) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// Hotbar selects a slot.
type Hotbar struct {
	Slot uint32 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
}

func (m *Hotbar) Reset()         { *m = Hotbar{} }
func (m *Hotbar) String() string { return proto.CompactTextString(m) }
func (*Hotbar) ProtoMessage()    {}
func (*Hotbar) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c15964ef051280e, []int{8}
}
func (m *Hotbar) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Hotbar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Hotbar.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Hotbar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hotbar.Merge(m, src)
}
func (m *Hotbar) XXX_Size() int {
	return m.Size()
}
func (m *Hotbar) XXX_DiscardUnknown() {
	xxx_messageInfo_Hotbar.DiscardUnknown(m)
}

var xxx_messageInfo_Hotbar proto.InternalMessageInfo

func (m *Hotbar) GetSlot() uint32 {
	if m != nil {
		return m.Slot
	}
	return 0
}

// Action is one thing the player did during one tick.
type Action struct {
	// Types that are valid to be assigned to Kind:
	//
	//	*Action_Move
	//	*Action_Dig
	//	*Action_Place
	//	*Action_Chat
	//	*Action_Hotbar
	Kind isAction_Kind `protobuf_oneof:"kind"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c15964ef051280e, []int{9}
}
func (m *Action) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Action.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return m.Size()
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

type isAction_Kind interface {
	isAction_Kind()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Action_Move struct {
	Move *Move `protobuf:"bytes,1,opt,name=move,proto3,oneof" json:"move,omitempty"`
}
type Action_Dig struct {
	Dig *Dig `protobuf:"bytes,2,opt,name=dig,proto3,oneof" json:"dig,omitempty"`
}
type Action_Place struct {
	Place *Place `protobuf:"bytes,3,opt,name=place,proto3,oneof" json:"place,omitempty"`
}
type Action_Chat struct {
	Chat *Chat `protobuf:"bytes,4,opt,name=chat,proto3,oneof" json:"chat,omitempty"`
}
type Action_Hotbar struct {
	Hotbar *Hotbar `protobuf:"bytes,5,opt,name=hotbar,proto3,oneof" json:"hotbar,omitempty"`
}

func (*Action_Move) isAction_Kind()   {}
func (*Action_Dig) isAction_Kind()    {}
func (*Action_Place) isAction_Kind()  {}
func (*Action_Chat) isAction_Kind()   {}
func (*Action_Hotbar) isAction_Kind() {}

func (m *Action) GetKind() isAction_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *Action) GetMove() *Move {
	if x, ok := m.GetKind().(*Action_Move); ok {
		return x.Move
	}
	return nil
}

func (m *Action) GetDig() *Dig {
	if x, ok := m.GetKind().(*Action_Dig); ok {
		return x.Dig
	}
	return nil
}

func (m *Action) GetPlace() *Place {
	if x, ok := m.GetKind().(*Action_Place); ok {
		return x.Place
	}
	return nil
}

func (m *Action) GetChat() *Chat {
	if x, ok := m.GetKind().(*Action_Chat); ok {
		return x.Chat
	}
	return nil
}

func (m *Action) GetHotbar() *Hotbar {
	if x, ok := m.GetKind().(*Action_Hotbar); ok {
		return x.Hotbar
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Action) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Action_Move)(nil),
		(*Action_Dig)(nil),
		(*Action_Place)(nil),
		(*Action_Chat)(nil),
		(*Action_Hotbar)(nil),
	}
}

// TickLog is everything that happened in one block, in the order it happened.
//
// Replaying these from tick 0 rebuilds the world, which is why this and not
// the world itself is what the chain is really storing.
type TickLog struct {
	Actions []Action `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions"`
}

func (m *TickLog) Reset()         { *m = TickLog{} }
func (m *TickLog) String() string { return proto.CompactTextString(m) }
func (*TickLog) ProtoMessage()    {}
func (*TickLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c15964ef051280e, []int{10}
}
func (m *TickLog) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TickLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TickLog.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TickLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TickLog.Merge(m, src)
}
func (m *TickLog) XXX_Size() int {
	return m.Size()
}
func (m *TickLog) XXX_DiscardUnknown() {
	xxx_messageInfo_TickLog.DiscardUnknown(m)
}

var xxx_messageInfo_TickLog proto.InternalMessageInfo

func (m *TickLog) GetActions() []Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

// LogEntry is one tick's actions, as the log hands them back.
type LogEntry struct {
	Tick    uint64   `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Actions []Action `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c15964ef051280e, []int{11}
}
func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(m, src)
}
func (m *LogEntry) XXX_Size() int {
	return m.Size()
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetTick() uint64 {
	if m != nil {
		return m.Tick
	}
	return 0
}

func (m *LogEntry) GetActions() []Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

// BlockEdit is one block that differs from the generated world.
type BlockEdit struct {
	Pos   BlockPos `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos"`
	State uint32   `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (m *BlockEdit) Reset()         { *m = BlockEdit{} }
func (m *BlockEdit) String() string { return proto.CompactTextString(m) }
func (*BlockEdit) ProtoMessage()    {}
func (*BlockEdit) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c15964ef051280e, []int{12}
}
func (m *BlockEdit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BlockEdit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BlockEdit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BlockEdit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockEdit.Merge(m, src)
}
func (m *BlockEdit) XXX_Size() int {
	return m.Size()
}
func (m *BlockEdit) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockEdit.DiscardUnknown(m)
}

var xxx_messageInfo_BlockEdit proto.InternalMessageInfo

func (m *BlockEdit) GetPos() BlockPos {
	if m != nil {
		return m.Pos
	}
	return BlockPos{}
}

func (m *BlockEdit) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "gaia.mc.v1.Params")
	proto.RegisterType((*GameState)(nil), "gaia.mc.v1.GameState")
	proto.RegisterType((*Player)(nil), "gaia.mc.v1.Player")
	proto.RegisterType((*BlockPos)(nil), "gaia.mc.v1.BlockPos")
	proto.RegisterType((*Move)(nil), "gaia.mc.v1.Move")
	proto.RegisterType((*Dig)(nil), "gaia.mc.v1.Dig")
	proto.RegisterType((*Place)(nil), "gaia.mc.v1.Place")
	proto.RegisterType((*Chat)(nil), "gaia.mc.v1.Chat")
	proto.RegisterType((*Hotbar)(nil), "gaia.mc.v1.Hotbar")
	proto.RegisterType((*Action)(nil), "gaia.mc.v1.Action")
	proto.RegisterType((*TickLog)(nil), "gaia.mc.v1.TickLog")
	proto.RegisterType((*LogEntry)(nil), "gaia.mc.v1.LogEntry")
	proto.RegisterType((*BlockEdit)(nil), "gaia.mc.v1.BlockEdit")
}

func init() { proto.RegisterFile("gaia/mc/v1/mc.proto", fileDescriptor_3c15964ef051280e) }

var fileDescriptor_3c15964ef051280e = []byte{
	// 740 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xc1, 0x6e, 0xdb, 0x46,
	0x10, 0xe5, 0x9a, 0x14, 0x2d, 0x8d, 0x6c, 0xd8, 0xde, 0x0a, 0x05, 0xed, 0xb6, 0xb2, 0xcc, 0x02,
	0x86, 0x5a, 0xb8, 0x12, 0x2c, 0xf7, 0x50, 0xb4, 0x68, 0x01, 0xab, 0x36, 0x2c, 0xa0, 0x2e, 0x2a,
	0xd0, 0x3d, 0xe5, 0x22, 0xac, 0x28, 0x82, 0x64, 0x44, 0x72, 0x05, 0x72, 0xad, 0x48, 0xfe, 0x84,
	0x9c, 0xf2, 0x09, 0x39, 0xe6, 0x98, 0x43, 0x3e, 0xc2, 0x47, 0x23, 0xa7, 0x00, 0x01, 0x8c, 0xc0,
	0x3e, 0x24, 0x9f, 0x11, 0xec, 0x2c, 0x15, 0xcb, 0x86, 0x13, 0x24, 0x40, 0x2e, 0xc4, 0xce, 0xdb,
	0xb7, 0xb3, 0xef, 0xcd, 0x0c, 0x17, 0xbe, 0xf1, 0x59, 0xc8, 0x9a, 0xb1, 0xdb, 0x1c, 0xef, 0x36,
	0x63, 0xb7, 0x31, 0x4a, 0xb9, 0xe0, 0x14, 0x24, 0xd8, 0x88, 0xdd, 0xc6, 0x78, 0x77, 0xa3, 0xe2,
	0x73, 0x9f, 0x23, 0xdc, 0x94, 0x2b, 0xc5, 0xd8, 0x58, 0x63, 0x71, 0x98, 0xf0, 0x26, 0x7e, 0x73,
	0x68, 0xdd, 0xe5, 0x59, 0xcc, 0xb3, 0x9e, 0xe2, 0xaa, 0x40, 0x6d, 0xd9, 0xcf, 0x08, 0x98, 0x5d,
	0x96, 0xb2, 0x38, 0xa3, 0xdb, 0xb0, 0x22, 0x42, 0x77, 0x98, 0xf5, 0x46, 0x5e, 0xda, 0xeb, 0x47,
	0xdc, 0x1d, 0x5a, 0xa4, 0x46, 0xea, 0xcb, 0xce, 0x32, 0xc2, 0x5d, 0x2f, 0x6d, 0x4b, 0x90, 0xfe,
	0x06, 0xe0, 0xf2, 0x44, 0xa4, 0x3c, 0x8a, 0xbc, 0xd4, 0x5a, 0xa8, 0x91, 0x7a, 0xa9, 0x6d, 0xbd,
	0x7c, 0xf1, 0x4b, 0x25, 0x4f, 0xbc, 0x3f, 0x18, 0xa4, 0x5e, 0x96, 0x9d, 0x88, 0x34, 0x4c, 0x7c,
	0x67, 0x8e, 0x4b, 0xb7, 0x60, 0xc9, 0x4f, 0xf9, 0x69, 0x32, 0xe8, 0x45, 0xde, 0xd8, 0x8b, 0x2c,
	0xbd, 0x46, 0xea, 0x05, 0xa7, 0xac, 0xb0, 0x63, 0x09, 0xfd, 0xbe, 0xfe, 0xee, 0xe9, 0x26, 0x79,
	0xfc, 0xf6, 0xf9, 0xcf, 0xab, 0xe8, 0x7e, 0x22, 0xfd, 0x2b, 0x7d, 0xf6, 0x5f, 0x50, 0x3a, 0x62,
	0xb1, 0x77, 0x22, 0x98, 0xf0, 0x28, 0x05, 0x43, 0xaa, 0x42, 0x85, 0x86, 0x83, 0x6b, 0xfa, 0x03,
	0x40, 0x26, 0x37, 0x7b, 0x01, 0xcb, 0x02, 0x14, 0xb6, 0xe4, 0x94, 0x10, 0xe9, 0xb0, 0x2c, 0xb0,
	0x5f, 0x4b, 0xab, 0x11, 0x9b, 0x7a, 0x29, 0x6d, 0xc1, 0x22, 0x53, 0x2a, 0x31, 0xc1, 0xa7, 0xf4,
	0xcf, 0x88, 0x74, 0x09, 0xc8, 0x04, 0x93, 0xea, 0x0e, 0x99, 0xc8, 0x68, 0x8a, 0xfa, 0x75, 0x87,
	0x4c, 0x65, 0x74, 0x66, 0x19, 0x2a, 0x3a, 0xa3, 0xab, 0xa0, 0x4f, 0xd9, 0x23, 0xab, 0x80, 0xee,
	0xe4, 0x92, 0x56, 0xa0, 0x30, 0x0a, 0x85, 0x1b, 0x58, 0x26, 0x62, 0x2a, 0xa0, 0xdf, 0x41, 0x89,
	0x27, 0x3d, 0xe5, 0xde, 0x5a, 0xac, 0x91, 0x7a, 0xd1, 0x29, 0xf2, 0xe4, 0x08, 0x63, 0xfa, 0x2d,
	0x98, 0x01, 0x17, 0x7d, 0x96, 0x5a, 0x45, 0x6c, 0x42, 0x1e, 0x49, 0xfc, 0x21, 0x0f, 0x13, 0x6f,
	0x60, 0x95, 0xf0, 0x44, 0x1e, 0xd9, 0xbf, 0x42, 0x11, 0xdb, 0xd3, 0xe5, 0xb9, 0x54, 0x82, 0x57,
	0xcd, 0xa4, 0x2e, 0xa8, 0x28, 0x97, 0xaa, 0x0a, 0x4f, 0xce, 0xec, 0x53, 0x30, 0xfe, 0xe5, 0x63,
	0xef, 0xe6, 0x84, 0x7e, 0xeb, 0x84, 0x7e, 0xeb, 0xc4, 0xbc, 0x39, 0xe3, 0x1e, 0x73, 0x85, 0x8f,
	0x9a, 0x33, 0x6f, 0x9b, 0xb3, 0xf7, 0x40, 0x3f, 0x08, 0x7d, 0xba, 0x03, 0xfa, 0x88, 0xab, 0x16,
	0x94, 0x5b, 0x95, 0xc6, 0xcd, 0x68, 0x37, 0x66, 0x56, 0xda, 0xc6, 0xf9, 0xe5, 0xa6, 0xe6, 0x48,
	0x9a, 0xfd, 0x0f, 0x14, 0xba, 0x11, 0x73, 0xbd, 0x2f, 0x3b, 0x26, 0xe5, 0xe1, 0x0c, 0xa0, 0xa1,
	0x65, 0x47, 0x05, 0xf6, 0x06, 0x18, 0x7f, 0x07, 0x4c, 0xe0, 0x1c, 0x79, 0x13, 0xa1, 0xc6, 0xc0,
	0xc1, 0xb5, 0xfd, 0x3d, 0x98, 0x1d, 0x55, 0x6c, 0x0a, 0x46, 0x16, 0x71, 0x91, 0xff, 0x07, 0xb8,
	0xb6, 0x2f, 0x09, 0x98, 0xfb, 0xae, 0x08, 0x79, 0x42, 0xb7, 0xc1, 0x88, 0xf9, 0xd8, 0xcb, 0x95,
	0xac, 0xce, 0x2b, 0x91, 0x55, 0xed, 0x68, 0x0e, 0xee, 0xd3, 0x1f, 0x41, 0x1f, 0x84, 0x3e, 0x0a,
	0x28, 0xb7, 0x56, 0xe6, 0x69, 0x07, 0xa1, 0xdf, 0xd1, 0x1c, 0xb9, 0x4b, 0x7f, 0x82, 0xc2, 0x48,
	0xda, 0xc3, 0x52, 0x97, 0x5b, 0x6b, 0xf3, 0x34, 0xf4, 0xdd, 0xd1, 0x1c, 0xc5, 0x90, 0xf7, 0xba,
	0x01, 0x13, 0xd8, 0x84, 0x3b, 0xf7, 0x4a, 0x53, 0xf2, 0x5e, 0xb9, 0x4f, 0x77, 0x3e, 0xcc, 0x50,
	0x01, 0x99, 0x74, 0x9e, 0xa9, 0x2c, 0x76, 0xb4, 0xd9, 0x64, 0xb5, 0x4d, 0x30, 0x86, 0x61, 0x32,
	0xb0, 0xff, 0x84, 0xc5, 0xff, 0x43, 0x77, 0x78, 0xcc, 0x7d, 0xfc, 0x4f, 0xd0, 0xaa, 0xac, 0xb6,
	0x7e, 0x37, 0x83, 0xaa, 0x42, 0x5e, 0xeb, 0x19, 0xd1, 0x76, 0xa0, 0x78, 0xcc, 0xfd, 0xc3, 0x44,
	0xa4, 0xd3, 0x7b, 0xff, 0xd2, 0xb9, 0x9c, 0x0b, 0x9f, 0x9b, 0xf3, 0x3f, 0x28, 0x61, 0x6b, 0x0f,
	0x07, 0xa1, 0xf8, 0x1a, 0xed, 0x6f, 0xff, 0x71, 0x7e, 0x55, 0x25, 0x17, 0x57, 0x55, 0xf2, 0xe6,
	0xaa, 0x4a, 0x9e, 0x5c, 0x57, 0xb5, 0x8b, 0xeb, 0xaa, 0xf6, 0xea, 0xba, 0xaa, 0x3d, 0xd8, 0xf2,
	0x43, 0x11, 0x9c, 0xf6, 0x1b, 0x2e, 0x8f, 0xf3, 0x97, 0xb2, 0x79, 0xf3, 0x12, 0x89, 0xe9, 0xc8,
	0xcb, 0xfa, 0x26, 0x3e, 0x9d, 0x7b, 0xef, 0x03, 0x00, 0x00, 0xff, 0xff, 0x16, 0x7e, 0x86, 0xc8,
	0xa1, 0x05, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TicksPerBlock != that1.TicksPerBlock {
		return false
	}
	if this.Controller != that1.Controller {
		return false
	}
	if this.GroundLevel != that1.GroundLevel {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.GroundLevel != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.GroundLevel))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Controller) > 0 {
		i -= len(m.Controller)
		copy(dAtA[i:], m.Controller)
		i = encodeVarintMc(dAtA, i, uint64(len(m.Controller)))
		i--
		dAtA[i] = 0x12
	}
	if m.TicksPerBlock != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.TicksPerBlock))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GameState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GameState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GameState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StateHash) > 0 {
		i -= len(m.StateHash)
		copy(dAtA[i:], m.StateHash)
		i = encodeVarintMc(dAtA, i, uint64(len(m.StateHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.Tick != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.Tick))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Player) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Player) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Player) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Joined {
		i--
		if m.Joined {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if m.Hotbar != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.Hotbar))
		i--
		dAtA[i] = 0x40
	}
	if m.OnGround {
		i--
		if m.OnGround {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.Pitch != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.Pitch))
		i--
		dAtA[i] = 0x30
	}
	if m.Yaw != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.Yaw))
		i--
		dAtA[i] = 0x28
	}
	if m.Z != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.Z))
		i--
		dAtA[i] = 0x20
	}
	if m.Y != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.Y))
		i--
		dAtA[i] = 0x18
	}
	if m.X != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.X))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintMc(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BlockPos) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlockPos) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BlockPos) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Z != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.Z))
		i--
		dAtA[i] = 0x18
	}
	if m.Y != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.Y))
		i--
		dAtA[i] = 0x10
	}
	if m.X != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.X))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Move) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Move) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Move) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OnGround {
		i--
		if m.OnGround {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.Pitch != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.Pitch))
		i--
		dAtA[i] = 0x28
	}
	if m.Yaw != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.Yaw))
		i--
		dAtA[i] = 0x20
	}
	if m.Z != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.Z))
		i--
		dAtA[i] = 0x18
	}
	if m.Y != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.Y))
		i--
		dAtA[i] = 0x10
	}
	if m.X != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.X))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Dig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Dig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Dig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Pos.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMc(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Place) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Place) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Place) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.State != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Pos.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMc(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Chat) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Chat) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Chat) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Text) > 0 {
		i -= len(m.Text)
		copy(dAtA[i:], m.Text)
		i = encodeVarintMc(dAtA, i, uint64(len(m.Text)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Hotbar) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Hotbar) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Hotbar) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Slot != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.Slot))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Action) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Action) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Action) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Kind != nil {
		{
			size := m.Kind.Size()
			i -= size
			if _, err := m.Kind.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *Action_Move) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Action_Move) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Move != nil {
		{
			size, err := m.Move.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *Action_Dig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Action_Dig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Dig != nil {
		{
			size, err := m.Dig.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *Action_Place) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Action_Place) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Place != nil {
		{
			size, err := m.Place.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *Action_Chat) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Action_Chat) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Chat != nil {
		{
			size, err := m.Chat.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *Action_Hotbar) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Action_Hotbar) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Hotbar != nil {
		{
			size, err := m.Hotbar.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}
func (m *TickLog) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TickLog) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TickLog) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Actions) > 0 {
		for iNdEx := len(m.Actions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Actions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMc(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *LogEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LogEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LogEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Actions) > 0 {
		for iNdEx := len(m.Actions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Actions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMc(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Tick != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.Tick))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BlockEdit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlockEdit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BlockEdit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.State != 0 {
		i = encodeVarintMc(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Pos.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMc(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintMc(dAtA []byte, offset int, v uint64) int {
	offset -= sovMc(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TicksPerBlock != 0 {
		n += 1 + sovMc(uint64(m.TicksPerBlock))
	}
	l = len(m.Controller)
	if l > 0 {
		n += 1 + l + sovMc(uint64(l))
	}
	if m.GroundLevel != 0 {
		n += 1 + sovMc(uint64(m.GroundLevel))
	}
	return n
}

func (m *GameState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Tick != 0 {
		n += 1 + sovMc(uint64(m.Tick))
	}
	l = len(m.StateHash)
	if l > 0 {
		n += 1 + l + sovMc(uint64(l))
	}
	return n
}

func (m *Player) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovMc(uint64(l))
	}
	if m.X != 0 {
		n += 1 + sovMc(uint64(m.X))
	}
	if m.Y != 0 {
		n += 1 + sovMc(uint64(m.Y))
	}
	if m.Z != 0 {
		n += 1 + sovMc(uint64(m.Z))
	}
	if m.Yaw != 0 {
		n += 1 + sovMc(uint64(m.Yaw))
	}
	if m.Pitch != 0 {
		n += 1 + sovMc(uint64(m.Pitch))
	}
	if m.OnGround {
		n += 2
	}
	if m.Hotbar != 0 {
		n += 1 + sovMc(uint64(m.Hotbar))
	}
	if m.Joined {
		n += 2
	}
	return n
}

func (m *BlockPos) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.X != 0 {
		n += 1 + sovMc(uint64(m.X))
	}
	if m.Y != 0 {
		n += 1 + sovMc(uint64(m.Y))
	}
	if m.Z != 0 {
		n += 1 + sovMc(uint64(m.Z))
	}
	return n
}

func (m *Move) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.X != 0 {
		n += 1 + sovMc(uint64(m.X))
	}
	if m.Y != 0 {
		n += 1 + sovMc(uint64(m.Y))
	}
	if m.Z != 0 {
		n += 1 + sovMc(uint64(m.Z))
	}
	if m.Yaw != 0 {
		n += 1 + sovMc(uint64(m.Yaw))
	}
	if m.Pitch != 0 {
		n += 1 + sovMc(uint64(m.Pitch))
	}
	if m.OnGround {
		n += 2
	}
	return n
}

func (m *Dig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Pos.Size()
	n += 1 + l + sovMc(uint64(l))
	return n
}

func (m *Place) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Pos.Size()
	n += 1 + l + sovMc(uint64(l))
	if m.State != 0 {
		n += 1 + sovMc(uint64(m.State))
	}
	return n
}

func (m *Chat) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Text)
	if l > 0 {
		n += 1 + l + sovMc(uint64(l))
	}
	return n
}

func (m *Hotbar) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Slot != 0 {
		n += 1 + sovMc(uint64(m.Slot))
	}
	return n
}

func (m *Action) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Kind != nil {
		n += m.Kind.Size()
	}
	return n
}

func (m *Action_Move) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Move != nil {
		l = m.Move.Size()
		n += 1 + l + sovMc(uint64(l))
	}
	return n
}
func (m *Action_Dig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Dig != nil {
		l = m.Dig.Size()
		n += 1 + l + sovMc(uint64(l))
	}
	return n
}
func (m *Action_Place) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Place != nil {
		l = m.Place.Size()
		n += 1 + l + sovMc(uint64(l))
	}
	return n
}
func (m *Action_Chat) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Chat != nil {
		l = m.Chat.Size()
		n += 1 + l + sovMc(uint64(l))
	}
	return n
}
func (m *Action_Hotbar) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Hotbar != nil {
		l = m.Hotbar.Size()
		n += 1 + l + sovMc(uint64(l))
	}
	return n
}
func (m *TickLog) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Actions) > 0 {
		for _, e := range m.Actions {
			l = e.Size()
			n += 1 + l + sovMc(uint64(l))
		}
	}
	return n
}

func (m *LogEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Tick != 0 {
		n += 1 + sovMc(uint64(m.Tick))
	}
	if len(m.Actions) > 0 {
		for _, e := range m.Actions {
			l = e.Size()
			n += 1 + l + sovMc(uint64(l))
		}
	}
	return n
}

func (m *BlockEdit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Pos.Size()
	n += 1 + l + sovMc(uint64(l))
	if m.State != 0 {
		n += 1 + sovMc(uint64(m.State))
	}
	return n
}

func sovMc(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMc(x uint64) (n int) {
	return sovMc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TicksPerBlock", wireType)
			}
			m.TicksPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TicksPerBlock |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Controller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Controller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroundLevel", wireType)
			}
			m.GroundLevel = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GroundLevel |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GameState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GameState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GameState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tick", wireType)
			}
			m.Tick = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tick |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMc
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateHash = append(m.StateHash[:0], dAtA[iNdEx:postIndex]...)
			if m.StateHash == nil {
				m.StateHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Player) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Player: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Player: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field X", wireType)
			}
			m.X = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.X |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Y", wireType)
			}
			m.Y = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Y |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Z", wireType)
			}
			m.Z = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Z |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Yaw", wireType)
			}
			m.Yaw = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Yaw |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pitch", wireType)
			}
			m.Pitch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Pitch |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OnGround", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OnGround = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hotbar", wireType)
			}
			m.Hotbar = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Hotbar |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Joined", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Joined = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipMc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BlockPos) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlockPos: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlockPos: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field X", wireType)
			}
			m.X = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.X |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Y", wireType)
			}
			m.Y = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Y |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Z", wireType)
			}
			m.Z = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Z |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Move) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Move: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Move: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field X", wireType)
			}
			m.X = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.X |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Y", wireType)
			}
			m.Y = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Y |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Z", wireType)
			}
			m.Z = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Z |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Yaw", wireType)
			}
			m.Yaw = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Yaw |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pitch", wireType)
			}
			m.Pitch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Pitch |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OnGround", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OnGround = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipMc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Dig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Dig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Dig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Pos.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Place) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Place: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Place: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Pos.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Chat) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Chat: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Chat: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Text", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Text = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Hotbar) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Hotbar: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Hotbar: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slot", wireType)
			}
			m.Slot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Slot |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Action) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Action: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Action: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Move", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Move{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Kind = &Action_Move{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Dig{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Kind = &Action_Dig{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Place", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Place{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Kind = &Action_Place{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chat", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Chat{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Kind = &Action_Chat{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hotbar", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Hotbar{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Kind = &Action_Hotbar{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TickLog) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TickLog: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TickLog: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Actions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Actions = append(m.Actions, Action{})
			if err := m.Actions[len(m.Actions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LogEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LogEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LogEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tick", wireType)
			}
			m.Tick = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tick |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Actions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Actions = append(m.Actions, Action{})
			if err := m.Actions[len(m.Actions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BlockEdit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlockEdit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlockEdit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Pos.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMc
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMc
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMc
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMc        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMc          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMc = fmt.Errorf("proto: unexpected end of group")
)
